name: Cleaning

on:
  pull_request:
    types:
      - closed

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
      - name: Delete
        env:
          BRANCH: ${{github.event.pull_request.head.ref}}
        run: git push origin --delete $BRANCH
