name: Creating

on:
  workflow_dispatch:
    inputs:
      formula:
        description: Formula name
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create package
        env:
          HOMEBREW_BINTRAY_REPO: dawidd6/bottles-tap
          HOMEBREW_BINTRAY_USER: ${{secrets.HOMEBREW_BINTRAY_USER}}
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          FORMULA: ${{github.event.inputs.formula}}
        run: |
          curl \
            --fail \
            --silent \
            --user $HOMEBREW_BINTRAY_USER:$HOMEBREW_BINTRAY_KEY \
            --header "Content-Type: application/json" \
            --data " \
             {\"name\": \"$(echo $FORMULA | tr '@' ':' | tr '+' 'x')\", \
              \"vcs_url\": \"$GITHUB_REPOSITORY\", \
              \"licenses\": [\"MIT\"], \
              \"public_download_numbers\": true, \
              \"public_stats\": true \
              }" \
            https://api.bintray.com/packages/$HOMEBREW_BINTRAY_REPO
