name: Main

on: pull_request

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    container:
      image: linuxbrew/brew
      env:
        # Invalid cross-device link error
        # Seems like github is mounting some volumes in home and workdir place
        HOMEBREW_CACHE: /home/linuxbrew/.cache
        HOMEBREW_TEMP: /home/linuxbrew/.tmp
        HOMEBREW_TAP: dawidd6/tap
        HOMEBREW_BINTRAY_REPO: dawidd6/bottles-tap
        HOMEBREW_BINTRAY_USER: dawidd6
        HOMEBREW_BINTRAY_URL: https://dl.bintray.com/dawidd6/bottles-tap
    steps:
      - name: Setup git
        run: |
          git config --global user.email "dawidd0811@gmail.com"
          git config --global user.name "dawidd6"
      - name: Build bottle
        # consistent working directory for both steps
        # to workaround: Invalid cross-device link error
        working-directory: /home/linuxbrew
        run: |
          # build bottle
          brew test-bot \
            --verbose \
            --bintray-org=$HOMEBREW_BINTRAY_USER \
            --root-url=$HOMEBREW_BINTRAY_URL \
            --tap=$HOMEBREW_TAP
      - name: Upload bottle
        # consistent working directory for both steps
        # to workaround: Invalid cross-device link error
        working-directory: /home/linuxbrew
        # only run if build was successful
        if: success()
        env:
          # secret bintray API key
          HOMEBREW_BINTRAY_KEY: ${{ secrets.HOMEBREW_BINTRAY_KEY }}
          # this url is needed for proper check if filename_already_published
          HOMEBREW_BOTTLE_DOMAIN: https://bintray.com/dawidd6
        run: |
          # gracefully exit if no bottles
          test -z "$(find . -name '*.bottle.*')" && exit
          # run `brew update` so we hopefully avoid:
          # "Formula loading disabled by HOMEBREW_DISABLE_LOAD_FORMULA!"
          brew update
          # install this utility so we can create packages
          brew install jfrog-cli-go
          # get package name
          PACKAGE="$(ls *bottle.json | cut -d- -f1)"
          # create package if it doesn't exist
          jfrog bt package-show \
            --user=$HOMEBREW_BINTRAY_USER \
            --key=$HOMEBREW_BINTRAY_KEY \
            $HOMEBREW_BINTRAY_REPO/$PACKAGE || \
          jfrog bt package-create \
            --user=$HOMEBREW_BINTRAY_USER \
            --key=$HOMEBREW_BINTRAY_KEY \
            --vcs-url=$GITHUB_REPOSITORY \
            --licenses=MIT \
            $HOMEBREW_BINTRAY_REPO/$PACKAGE
          # upload bottle from current directory
          brew test-bot \
            --verbose \
            --bintray-org=$HOMEBREW_BINTRAY_USER \
            --root-url=$HOMEBREW_BINTRAY_URL \
            --ci-upload
